# Generated by Django 5.0.6 on 2024-05-21 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonctionnalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Fonctionnalité',
                'verbose_name_plural': 'Fonctionnalités',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Soumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=10)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('conditions_acceptees', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Forfait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_forfait', models.CharField(max_length=255)),
                ('prix_abonnement', models.PositiveBigIntegerField()),
                ('type_abonnement', models.CharField(choices=[('gratuit', 'Inscription GRATUITE'), ('visibilite_web', 'Forfait visibilité web '), ('strategie_marketing', 'Forfait stratégie marketing'), ('developpement_affaires', 'Forfait développement des affaires')], max_length=30)),
                ('fonctionnalites', models.ManyToManyField(to='base.fonctionnalite')),
            ],
            options={
                'verbose_name': 'Forfait',
                'verbose_name_plural': 'Forfaits',
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description_courte', models.TextField()),
                ('site_web', models.URLField()),
                ('logo', models.ImageField(upload_to='logos/')),
                ('derniere_realisation', models.TextField()),
                ('texte_presentation', models.TextField()),
                ('avantages', models.TextField()),
                ('courte_description_seo', models.TextField()),
                ('courte_description_entreprise', models.TextField()),
                ('page_presentation', models.BooleanField(default=False)),
                ('code_promotionnel', models.CharField(blank=True, max_length=50, null=True)),
                ('pourcentage_remise', models.IntegerField(default=10)),
                ('conditions_acceptees', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forfait', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.forfait')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.service')),
            ],
            options={
                'verbose_name': 'Entrepreneur',
                'verbose_name_plural': 'Entrepreneurs',
            },
        ),
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('description_travaux', models.TextField()),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type_soummission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.type_soumission')),
            ],
        ),
    ]
