# Generated by Django 5.0.6 on 2024-05-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forfait',
            name='fonctionnalites',
            field=models.ManyToManyField(null=True, to='base.fonctionnalite'),
        ),
    ]
