# Generated by Django 5.0.6 on 2024-05-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_forfait_fonctionnalites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forfait',
            name='fonctionnalites',
            field=models.ManyToManyField(blank=True, to='base.fonctionnalite'),
        ),
    ]
