# Generated by Django 5.0.6 on 2024-05-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_forfait_fonctionnalites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Galleries')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
