# Generated by Django 5.0.6 on 2024-05-22 10:44

import markdownx.models
import slugger.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_realisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contenu', markdownx.models.MarkdownxField()),
                ('auteur', models.CharField(max_length=255)),
                ('date_publiaction', models.DateField(auto_now=True)),
                ('slug', slugger.fields.AutoSlugField(populate_from='titre', unique=True)),
            ],
        ),
    ]
