# Generated by Django 5.0.6 on 2024-05-25 13:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contenu',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
