# Generated by Django 5.0.6 on 2024-08-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_entreprise_nom_entreprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='nom_entreprise',
        ),
    ]
