# Generated by Django 5.0.6 on 2024-08-07 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_entreprise_nom_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='soumission',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.service'),
            preserve_default=False,
        ),
    ]
