# Generated by Django 5.0.6 on 2024-08-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_fonctionnalite_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realisation',
            options={'verbose_name': '', 'verbose_name_plural': 'Realisations'},
        ),
        migrations.AddField(
            model_name='entreprise',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
